function handleError(error) {
    alert(error)
}

function raiseError({ message }) {
    throw message
}